### ISSUE TITLE
FCS experiment: can't seek within first 30 minutes of file

### ISSUE THREAD

**Issue by atruskie** [QutEcoacoustics/interaction-experiments#2]
@Allcharles noticed the other day you can't click or drag seek within the first 30 minutes of the audio file.

We suspect it's a bug in MediaElement.js because we reproduced it cross-browser.

We also need to test if the problem happens in the native HTML5 audio element - I suspect it does not.

**Comment by Allcharles** [comment]
Just got my workbench running and the bug doesn't happen with the native HTML5 audio element for firefox and chrome.

**Comment by atruskie** [comment]
Great! Now to investigate mediaelement.js...

**Comment by Allcharles** [comment]
Okay so the bug only deals with the 0 second time point. Any other time point seems to function perfectly normal. So it seems that the problem is not a bug but a feature of the library.

**Comment by atruskie** [comment]
Can you explain further? 30minutes is not 0 seconds. Can you link to problematic source, or issues?

Do you have a suggestion for further action?

**Comment by Allcharles** [comment]
The issue only occurs when the timestamp of the audio file is close to 0 seconds. After 30 minutes into the audio source you are free to seek any amount that you want. Ive downloaded the source code an am taking a look to see if there is a setting i can flip to turn off the feature.

**Comment by atruskie** [comment]
Nice work
