### ISSUE TITLE
Disable tutorial progress bar interactivity

### ISSUE THREAD

**Issue by KellieVella** [QutEcoacoustics/interaction-experiments#3]
keep as visual feedback but lose the ability to use it to skip pages

**Comment by Allcharles** [comment]
Fixed in commit 30fde7dc17deefe550e3f92712c9f2b265b77068

**Comment by atruskie** [comment]
Hi @Allcharles, the pointer-events fix in 30fde7d is 👌 but can I get you to place it in the `carousel-maker.html` shortcode file, with a parameter to enable/disable it instead. Thanks.
