### ISSUE TITLE
Find out if annotorious accepts templates

### ISSUE THREAD

**Issue by KellieVella** [QutEcoacoustics/interaction-experiments#5]

**Comment by atruskie** [comment]
To add more context, if it does,

- We want to customize the text about commenting
- and also, add radio button options (or a dropdown) for some pages

**Comment by Allcharles** [comment]
Current Issues:
- Annotorious editor does not remember previous value when updating label for dropdown menus.

**Comment by atruskie** [comment]
Closed in 7d1bff192ca9a34b3d5ed8b6e59e9948fbadda10, 3ec1e0919fbe62eb2fe5da78d79ad8139d662fb9, 986bae3806f9e290e5ffd29bd150f99e2221ef87, ee9499bb25e31980d4650a7e724d396e88a89bbe, b55941f7cace96fa08e06f205c9b9529a738225d, e9196c60a154afeb7494b1a26fdcb7e0214da2cb.

Thanks @Allcharles.

We won't fix the select-right-label when editing bug. Given that we'll only be using a few labels, it's easy enough to keep a track of things.
