### ISSUE TITLE
Force 3 choices per screen during the search task

### ISSUE THREAD

**Issue by KellieVella** [QutEcoacoustics/interaction-experiments#7]
Search task (3 screens) only
- if the user attempts to continue to the next screen without having first boxed three things they are stopped from progressing with a warning "Box three sounds before continuing"

**Comment by atruskie** [comment]
Implementation: like other [jspsych plugins](https://www.jspsych.org/plugins/jspsych-external-html/), create an `check_fn` callback which if specified will advance only if it returns `true`.

In `experiment.js` add an the required `check_fn` implementation for the search task only.

**Comment by atruskie** [comment]
Closed in fd48a1e and 612e9cd6a11942ece84647fc6891d9a0883c5049
